two

diff --git a/.github/workflows/dockerpush.yml b/.github/workflows/dockerpush.yml
--- a/.github/workflows/dockerpush.yml
+++ b/.github/workflows/dockerpush.yml
@@ -11,7 +11,7 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout repository
-        uses: actions/checkout@v4
+        uses: actions/checkout@v3
 
       - name: Setup SSH
         run: |
@@ -24,7 +24,7 @@ jobs:
       - name: try remove existing image
         continue-on-error: true
         run: |
-          ssh -o StrictHostKeyChecking=no root@45.79.249.235 "docker rm -f runit || true"
+          ssh -o StrictHostKeyChecking=no root@45.79.249.235 "docker rm -f runit || true"  # Using `|| true` to ensure command exits with success even if docker rm fails
           ssh -o StrictHostKeyChecking=no root@45.79.249.235 "echo 'remove image'"
 
       - name: pull and install new image
