two

diff --git a/.github/workflows/dockerpush.yml b/.github/workflows/dockerpush.yml
--- a/.github/workflows/dockerpush.yml
+++ b/.github/workflows/dockerpush.yml
@@ -11,7 +11,7 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout repository
-        uses: actions/checkout@v3
+        uses: actions/checkout@v4
 
       - name: Setup SSH
         run: |
@@ -20,13 +20,18 @@ jobs:
           chmod 600 ~/.ssh/id_rsa
           ssh-keyscan -H 45.79.249.235 >> ~/.ssh/known_hosts
           ssh -o StrictHostKeyChecking=no root@45.79.249.235 "echo 'SSH connection successful'"
-          ssh -o StrictHostKeyChecking=no root@45.79.249.235 "docker rm -f runit"
+
+      - name: try remove existing image
+        continue-on-error: true
+        run: |
+          ssh -o StrictHostKeyChecking=no root@45.79.249.235 "docker rm -f runit || true"  # Using `|| true` to ensure command exits with success even if docker rm fails
           ssh -o StrictHostKeyChecking=no root@45.79.249.235 "echo 'remove image'"
+
+      - name: pull and install new image
+        run: |
           ssh -o StrictHostKeyChecking=no root@45.79.249.235 "docker run -d -t -p 5001:8000 -p 5002:3000 --name runit gnaskdiashvili/laravelvueinertia"
           ssh -o StrictHostKeyChecking=no root@45.79.249.235 "echo 'access image'"
           ssh -o StrictHostKeyChecking=no root@45.79.249.235 "docker exec -it runit bash"
           ssh -o StrictHostKeyChecking=no root@45.79.249.235 "service apache2 start"
-
-
         env:
           SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
